name: podcast_search
description: A library for searching for podcasts, parsing podcast RSS feeds and obtaining episodes details. Supports searching via iTunes and PodcastIndex (preview).

version: 0.5.0
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  convert: ^3.0.1
  crypto: ^3.0.1
  dio: ^5.3.2
  dart_rss: ^2.0.1
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
